### ISSUE TITLE
weight

### ISSUE THREAD

**Issue by darkvei** [B-iggy/HWS-Plus-Creative-Scenario#18]
if the resources are in the player's inventory, then the ship takes off, if you transfer it to the ship, it stops moving, how and where to start understanding whether the ship will take off or not, I can't understan
![20220629135520_1](https://user-images.githubusercontent.com/107724149/176421359-6a850158-d20a-49f7-bdc2-f9ea00c2f3c4.jpg)
![20220629135529_1](https://user-images.githubusercontent.com/107724149/176421375-99224ddb-f71f-4630-99d3-5324efb41522.jpg)
d

**Comment by B-iggy** [comment]
This is a game core "feature". In Vanilla, RE, everywhere.
The weight of the players backpack does not play a role when you sit in the cockpit. It is not added to the total weight carry capabilities of your ship - which makes no sense of course, but this is Empyrion.

So make sure your Thrusters can lift the weight you put in your containers.

**Comment by darkvei** [comment]
OK, do I need to add engines? So that I can take off?

**Comment by B-iggy** [comment]
Exactly. In your Control Panel > Statistics it is showing you if you can lift off.

**Comment by darkvei** [comment]
thanks

**Comment by darkvei** [comment]
the only thing is how to understand the weight if it shows zero in the load
![20220629143609_1](https://user-images.githubusercontent.com/107724149/176427511-47757dc0-dd4e-4454-8fea-8544e8bf3b6c.jpg)
?

**Comment by B-iggy** [comment]
You mean Volume? volume is zero, yes. Because I implemented with HWS+ a new logistic system.
Volume does only exist for commodity items now (raw diamonds for example). For the rest there is no volume, only stack size limits.

**Comment by darkvei** [comment]
I'll put it another way: let's say my ship can lift a ton, but since I don't have a weight display, it shows zero, how do I determine how much cargo I can put in to take off? by adding or removing cargo? or count on a calculator? Now I have 11 tons of statistics, how do I understand how many resources I can invest?

**Comment by darkvei** [comment]
I turned on 8 additional engines for thrust, but I still can't take off with a meager supply in the hol
![20220629145840_1](https://user-images.githubusercontent.com/107724149/176431313-b2536e78-1740-4f27-a51e-9655bdc46354.jpg)
d
